### ISSUE TITLE
install Rails on macbook

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#14]
Dail, I can help you with this.  I used these instructions: 

https://gorails.com/setup/osx/10.9-mavericks

and my notes are on  phylotastic-portal#27

**Comment by hdliv** [comment]
i had ruby and rbenv already installed and rails is there...but I am working with van to iron out some other problems that are occurring during `bundle install`

**Comment by arlin** [comment]
Did you see what I wrote for #27?  After you get postgresql installed using brew, try using 

env ARCHFLAGS="-arch x86_64" gem install pg -v '0.17.1'

**Comment by arlin** [comment]
This ticket is in the wrong repo.  @hdliv, I added you to the developer list so that I could assign this ticket to you and move it into "in progress", as you are working on it already.

**Comment by hdliv** [comment]
@arlin spent the morning reading about whatever bug is in osx-capitan.  the error i was getting with `bundle install` was:

 `mini_ssl.c:4:10: fatal error: 'openssl/bio.h' file not found`
`#include <openssl/bio.h>`

Following:  https://coderwall.com/p/c_fnsa/fix-openssl-errors-when-installing-ruby-gems-in-osx-10-11-el-capitan
verified if OpenSSL was actually installed, then ran
`bundle config build.puma --with-cppflags=-I$(brew --prefix openssl)/include`

I was able to run `bundle install`
