### ISSUE TITLE
Testing initial iOS App

### ISSUE THREAD

**Issue by hdliv** [phylotastic/Pt_Mobile_Application#15]

**Comment by hdliv** [comment]
Tested @thanhnh-infinity App on parts of textbooks, posters, and taking photos of printed binomial spp. at different distances.

**Comment by hdliv** [comment]
after meeting 18-Feb, I will send @thanhnh-infinity these data

**Comment by arlin** [comment]
Also did some tests.  The character recognition is much better.  We are experiencing some odd behavior, however.

**Comment by arlin** [comment]
<IMG_1820.JPG>

**Comment by arlin** [comment]
@hdliv, I think we are done with the kind of testing that was requested.  the next phase of testing will be with the MVP and our external testers.  can you move this ticket?
