### ISSUE TITLE
video-cast mobile app how-to

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#34]
1. write script
2. practice
3. record
4. edit

**Comment by hdliv** [comment]
practicing and will go back and write the script

**Comment by arlin** [comment]
@hdliv, I have not looked at these yet.  Let's set aside a time and go over them together, to think about what we want to do.

**Comment by hdliv** [comment]
@arlin no problem.  it was more of practice runs in both English and Portuguese
