### ISSUE TITLE
annotate "hard" images

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#35]
Dail, thanks for adding some photos in test/images/hard !

To complete this, we need the metadata added in test/images/hard.csv .  Look at medium.csv for examples.   Note that image quality and OCR-difficulty are too different things, e.g., hand-writing is a challenge even if the image quality is high.  Your images are all high quality, except perhaps that the cryptophyte poster is affected by glare and skew.

**Comment by hdliv** [comment]
working on it.  Interestingly, the handwriting is being captured
