### ISSUE TITLE
implement UX : notifications

### ISSUE THREAD

**Issue by thanhnh-infinity** [phylotastic/Pt_Mobile_Application#41]

**Comment by arlin** [comment]
@thanhnh-infinity, please provide more detail on this issue so that it can be reviewed.

**Comment by thanhnh-infinity** [comment]
This issues includes all notifications for user inside app. For example, notify user No network connection, notify user select a  list, confirm when user wants to delete, notify users when get new names, ...

In addition, there are some UX (user experience) such as navigations, landscape, portrait, stylesheet for each page...

**Comment by arlin** [comment]
Thanks.   I will just move this to "Done" as we have all seen the notifications.
