### ISSUE TITLE
how-to page

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#43]
Put a help or "?" icon in the bottom bar, link to HowTo page.  See suggested content here: 

https://github.com/phylotastic/Phylotastic_Mobile_Application/blob/master/design/howto_page.html

This looks good in Chalkboard SE font at size 14.

**Comment by thanhnh-infinity** [comment]
How-To page is added already. In Home Page, press the Help button in Footer, you can go to How-To page
