### ISSUE TITLE
minor routing bug

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#44]
I found a minor routing bug. Do this: 
1. from Home, choose Capture
==> alert box "please select a list..."
2. click OK to dismiss alert
3. now, choose a list (which is the right thing to do)
==> same alert box 
4. now, choose a list
==> goes to list page

**Comment by arlin** [comment]
This same bug happens in the Capture  view.  Choose "Use this image" when the image is blank.  App responds with alert.  Now try to choose from photo library.  App responds with alert.  Try it again, app is OK now.  

That is, there is some kind of "echo" effect here, by which the alert box is induced when a correct choice follows a wrong choice. 
right choice ==> no alert
wrong choice ==> alert
right choice ==> alert
right choice again ==> no alert

**Comment by thanhnh-infinity** [comment]
I've got this bug. It will be fixed in next release

**Comment by thanhnh-infinity** [comment]
But is fixed

**Comment by arlin** [comment]
Good to hear!  please move this ticket to "review" and i will review it.

**Comment by arlin** [comment]
I have tested this and the bug is gone.  Thanks.
