### ISSUE TITLE
delete name from list

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#45]
Allow user to delete name from list.

**Comment by epontell** [comment]
We talked with Abu Saleh last week about providing add/delete operations as part of the species list server. We need to the best "gestures" to reflect these operations in the App

**Comment by arlin** [comment]
swipe-to-delete is pretty standard, right?

**Comment by thanhnh-infinity** [comment]
Professors, right now, I do not use server (back-end to store species data). I stored them locally only. I think in next step, if you want to store them in server-side, we can create sync  mechanism between client and server. After complete them, all actions like add, edit, delete local data will be synced with data in server

**Comment by thanhnh-infinity** [comment]
You can swipe-to-right to delete species. Press OK to confirm delete

**Comment by hdliv** [comment]
it would also be nice to swipe and delete whole lists, not just single names in a list

**Comment by thanhnh-infinity** [comment]
If delete whole list, you can implement feature : go to master list and delete master list. Right now, this feature is not deployed. If it is approved, I will implement this. However, when go inside the list, swipe and delete only one single name each time is better than delete multiple names.

**Comment by hdliv** [comment]
There can be lists with 50+ names, so it would be easier to delete whole list instead of sliding 50+ names.  However smaller lists are easy to delete one by one, as said.
