### ISSUE TITLE
export tree

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#46]
Allow the user to export the tree in at least 1 way, such as email or send to browser.

**Comment by epontell** [comment]
Are we talking about the tree as a data structure (e.g., Newick string? NeXML?) or the image of the tree (e.g., exported to iPhone album?)

**Comment by arlin** [comment]
I'm talking about data.  Right now, we have created a data workflow with a dead end.  Some users are going to go nuts if they can't get that tree out of the app and look at it elsewhere.  Easy solution #1 is just have an "email to me" button.  Easy solution #2 is to have a button to "open in browser" (send the tree in the url to the view service, like we were doing before), then the user can use the browser's built-in features ("share this page").

**Comment by thanhnh-infinity** [comment]
Yes, I will create features "email to me" and "open in browser" in App after we had tree

**Comment by thanhnh-infinity** [comment]
Professors,

Press button Export in Header, you can select one of export methods. 

Right now, "Email to me" is not working because we need supports from server to allow receive tree data from app, send email to user (Open port to send email, develop email module, build mail server).

"Open in Browser" works well

**Comment by arlin** [comment]
Yes, this "Open in Browser" works well.  

Currently, if the user presses the "email to me" button, there is no feedback, so the user may assume that the tree has been mailed.  This could be a source of frustration-- the user would lose the tree after having tried to save it.  Please hide "Email to me" until it is working, or post an alert that says "Sorry!  This feature is not implemented yet".

**Comment by thanhnh-infinity** [comment]
Yes, Dr Arlin. I will hide "Email to me" button
