### ISSUE TITLE
Add help on 2 new features

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#52]
Add help on 2 new features as described in design/mobile_app_mvp_priorities.pptx .  

Also, try to reformat the style so that the help text does not take up so much space.

**Comment by thanhnh-infinity** [comment]
Fixed already. I made changes the content as you mentioned

**Comment by arlin** [comment]
This is good.  Were you able to make it more compact?  I don't see a difference.
