### ISSUE TITLE
De-clutter tree view

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#56]
De-clutter tree view by removing internal node labels and ottIds, as described in design/mobile_app_mvp_priorities.pptx

**Comment by thanhnh-infinity** [comment]
Removed open tree ottids in tree is done right now.

But I do not know how to remove internal node, because when I receive the newick tree from Web Services. They are existed. So I think we should remove them from server-side ? 

And If Yes, How can we remove them ?

**Comment by arlin** [comment]
we should find or develop toolbox code to do this, but if you just want a quick fix, I would suggest to use regular expressions-- probably something like  s/\)[^),;]+/)/g  will remove them.  Any name following a right parenthesis is an internal node name, and they will always be followed by either a comma or another right parenthesis or semi-colon if that's the end of the tree-string.

**Comment by thanhnh-infinity** [comment]
Oh, that is good suggestion. I will try to do follow your guide.

**Comment by thanhnh-infinity** [comment]
Fixed, I used /)[a-z|A-Z]+/g

**Comment by arlin** [comment]
My tests indicate that this is fixed.  Thanks!
