### ISSUE TITLE
More informative alert on login fail

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#62]
Add more informative alert message on login fail, as described in design/mobile_app_mvp_priorities.pptx

**Comment by arlin** [comment]
How do I test this?  I do not know how to make login fail.  The app remembers my login.

**Comment by thanhnh-infinity** [comment]
Hi @arlin . Please remove the app in your device ; confirm that you remove app's data. After that, re-install again from TestFlight. App will require you credential

**Comment by arlin** [comment]
OK, thanks.  I tested this and the error message is "Oops!  Username or password error.  Please try again"  

That's good. Thanks.  @thanhnh-infinity,  I have noticed several alert messages that (like the one above) end without a period (".").  Is that intended, or is the period getting lost?

**Comment by thanhnh-infinity** [comment]
Thanks Dr @arlin . I will add "." at the end of all messages in our app in next release
