### ISSUE TITLE
Alert for no-text-found

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#64]
Add alert for no-text-found, as described in design/mobile_app_mvp_priorities.pptx

**Comment by arlin** [comment]
I am not seeing an alert when I scrape from an image with no text.  I tried this twice.  
- choose image with no text
- choose "Use this image" 
  
  --> app alert with spinner says "Waiting for OCR engine..."
  --> return to Capture view with no other alert

**Comment by thanhnh-infinity** [comment]
Hi @arlin  . Fixed it already. Will be updated in the next release Version 0.0.2 build 0.0.5

**Comment by arlin** [comment]
Yes, thanks, that is very good.
