### ISSUE TITLE
can't escape embedded viewer

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#65]
Go to "Help".  
Click on any of the embedded links.  
The page then opens in an embedded viewer, but there are no controls.  I can see this is an embedded viewer because if I minimize the app, I can see that only the app is running and not Safari.  But I no longer have any navigation control from within the app.  I can't escape from the embedded viewer to return to any of the other views.  

We need to fix this.  It is very frustrating, because the only way out is to quit the app and then restart it.  The quick fix is just to disable all the links.  A better fix is to add a "return" button to the embedded viewer, or open the pages up in a separate browser app.  

Also, it was a mistake (on my part) to put a link to start a new github issue.  This isn't going to work even in a browser. The format is too small.  I need to rethink this.

**Comment by arlin** [comment]
BTW, I'm using an iPhone 5 version 8.1.2

**Comment by thanhnh-infinity** [comment]
Yes, Dr Arlin. It will be fixed in the next release

**Comment by arlin** [comment]
Thanks, I can verify that this launches the external browser in every case (OCR, OpenTree, GNRD, Phylotastic, and GitHub issue).
