### ISSUE TITLE
remove redundancy before adding to list

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#66]
Use image "multiple2.jpg" from mobile app repo (test/images/batch/longwood_gardens_multisigns).  Scrape names.  "Chambeyronia" appears 3 times on the sign, and is added to the list 3 times.  We should have a way to remove redundancy.

**Comment by thanhnh-infinity** [comment]
I fixed it in newest version

**Comment by arlin** [comment]
Thanks.  I tested this again with the same image and there are no longer any duplicate names.
