### ISSUE TITLE
3 scraped names returning 48 tips - no tips from original photo

### ISSUE THREAD

**Issue by hdliv** [phylotastic/Pt_Mobile_Application#67]
I put the image here: Phylotastic_Mobile_Application/test/images/hard/Eustigmatophyceae.jpg

OCR scrapes the 3 names, but the get tree returns 48 tips.  None of these tips are actually the 3 species from Eustigmatophyceae.jpg

Maybe an isolated case?

**Comment by arlin** [comment]
This is a bug in the underlying nmsu.edu services.  See phylotastic/phylo_webservices#12.  

I'm labeling this as "wontfix" and putting it into "Done"

**Comment by arlin** [comment]
On second thought, I'm going to leave this in "Ready" as a reminder and assign it to @hdliv, who should close this when phylotastic/phylo_webservices#12 is fixed and  he determines by testing that the problematic behavior no longer occurs.

**Comment by arlin** [comment]
@hdliv, I think this is fixed now.  Please try again when you have some time.

**Comment by hdliv** [comment]
@arlin it now provides a tree with either 1 tip or 2...

**Comment by arlin** [comment]
@hdliv, if you think this is fixed, then close it, please.

**Comment by hdliv** [comment]
@arlin I didnt close it since the app  went from scraping 3 names and getting 48 tips, to scraping 5 names and getting 2 or 1 tip.  should this stay on the same ticket or a new one?

**Comment by hdliv** [comment]
3tips to 48tips not happening anymore.  new issue will be created for 5names to 1-2 names
