### ISSUE TITLE
delete list

### ISSUE THREAD

**Issue by hdliv** [phylotastic/Pt_Mobile_Application#69]
with testing, I already have ~20 lists.  It would be nice to be able to delete.

**Comment by arlin** [comment]
I agree.  Offer capacity to delete list.  This could be done with swipe-to-delete or checkbox.

**Comment by thanhnh-infinity** [comment]
Swipe-to-delete is working for deleting a list of species names (in main page) inside master list in version 0.0.2 , build 0.0.7 . At the moment, the visualization for deletion in Home Page is same as in species names page. It means that the object is selected to delete will  be changed color to "red" in list and the confirmation box appears to confirm deleting. I am continue working on more beautiful graphic viz for deletion.

**Comment by hdliv** [comment]
i was able to delete lists :)

**Comment by arlin** [comment]
me too.  thanks!
