### ISSUE TITLE
deleting names from list, and they come back

### ISSUE THREAD

**Issue by hdliv** [phylotastic/Pt_Mobile_Application#70]
When deleting names from a list, and uploading the same photo again into the list... the names appear 2x, instead of keeping the previous extracted names deleted.

I tried with the following photos

Phylotastic_Mobile_Application/test/images/hard/Eustigmatophyceae.jpg

Phylotastic_Mobile_Application/test/images/hard/Ochromonas.jpg

Phylotastic_Mobile_Application/test/images/hard/CompositeToL3.jpg

**Comment by thanhnh-infinity** [comment]
This issue is fixed

**Comment by hdliv** [comment]
@thanhnh-infinity Phylotastic_Mobile_Application/test/images/hard/Eustigmatophyceae.jpg

before three names were scraped, but now 4.  one is the genus name alone

but what is odd is the tree: Pt_Mobile_Application/test/images/odd_tree2.jpg

**Comment by arlin** [comment]
@hdliv, could you please comment directly on whether the issue has been resolved or not?

**Comment by hdliv** [comment]
@arlin it seems so that is why i moved it to in review

**Comment by hdliv** [comment]
at least i think i did
