### ISSUE TITLE
tree viewer zoom limit

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#75]
I was unable to zoom out far enough to view a tree with only 23 tips.  The tree view was cut off at the bottom (missing one taxon), and the names were cut off at the right.  

http://128.123.177.13/Phylotastic_DisplayTree_Project/display_tree.html?uri=&tree_data=(Atticora%20tibialis,(((Sitta%20carolinensis,((Troglodytes%20aedon,Troglodytes%20hiemalis)Troglodytes,Microcerculus%20marginatus,(Cinnycerthia%20olivascens,Cinnycerthia%20peruana)Cinnycerthia,Henicorhina%20leucophrys,Cistothorus%20palustris,(Pheugopedius%20genibarbis,Pheugopedius%20eisenmanni)Pheugopedius,Campylorhynchus%20fasciatus,Cyphorhinus%20thoracicus)Troglodytinae),(((Turdus%20fuscater,Turdus%20ignobilis,Turdus%20leucops)Turdus,Myadestes%20ralloides,Entomodestes%20leucotis,(Catharus%20fuscater,Catharus%20dryas)Catharus)Turdidae,Cinclus%20leucocephalus)),(Catamenia%20analis,Spinus%20magellanicus)));&format=newick_text

**Comment by thanhnh-infinity** [comment]
Hi @arlin. You means this issues appeared in  viewing tree inside app (Tree View Page), or by exporting browser  ?

**Comment by arlin** [comment]
I can view in browser: 
![img_2056](https://cloud.githubusercontent.com/assets/1659198/14088741/249b2abc-f4ff-11e5-8d67-1158a379b3d5.PNG)
but not in app: 
 ![img_2055](https://cloud.githubusercontent.com/assets/1659198/14088711/1747ba2e-f4ff-11e5-8b7b-1fc1d73b5256.PNG)

**Comment by arlin** [comment]
note that this is the same issue as #73

**Comment by arlin** [comment]
I'm removing this as it is identical to #73
