### ISSUE TITLE
empty tree message

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#76]
Note that #72 is about timing out when underlying web services do not respond in time.  This ticket is about what happens when the tree service responds, but provides no tree.   
1. get list of dinosaur taxa from paleodb (https://paleobiodb.org/data1.2/taxa/list.txt?id=91968&rel=all_children&show=attr)
2.  use a text editor to make a list of species names 
3.  using mobile app, take photo of names on-screen 

--> app captures 17 names (in my case)
1.  select "get tree" 

--> app alert says "There is no data for tree"

I think this message is a bit confusing.  Can we change it to something like this?   "We're sorry.  We could not find phylogeny information for these species"

**Comment by thanhnh-infinity** [comment]
Yes, professor. Will fix it soon

**Comment by thanhnh-infinity** [comment]
@arlin It is fixed. Update will be affected from version 0.0.2 , build 0.0.5

**Comment by arlin** [comment]
OK, thanks.  I just downloaded the new version and this looks good.
