### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#77]
provide a means of individual authentication and account management, so that each user will have an account.  This could be done with google.

**Comment by thanhnh-infinity** [comment]
Dr @arlin , Could I make separately this ticket to 3 smaller tickets ? That could be easier to manage. 

Ticket 1 : Build Google OAuth 2.0 Client on Google Cloud Platform. After this step we will have client ID, client secret from Google that allow Mobile, Phylotastic server and Portal are able to work on credential together. => This ticket will be assigned to me @thanh-infinity

Ticket 2 : In Mobile App side, build Authentication feature that will use client ID and client secret in Ticket 1. When user uses Google account to login our application, app will obtain access_token from Google. After that, whenever app uses any Phylotastic server's Web Services, app has to attach access_token as a parameter of Web Service URL and submit to Phylotastic server. => This ticket will be assigned to me @thanhnh-infinity

Ticket 3 : In Phylotastic server side, Abu has to create module to obtain access_token that is submitted from mobile app ( and portal so far). And then this module  be able to check valid or in-valid access_token with Google to make sure that signed in Google account on app (and portal so far) has enough privileges to access Phylotastic Web Services. If Yes, Phylotastic server will return data, If NO, an exception will be returned. => This ticket will be assigned to @abusalehmdtayeen

**Comment by arlin** [comment]
Done.  This ticket will be labeled wontfix and moved to Done.

**Comment by thanhnh-infinity** [comment]
Thank you Dr Arlin
