### ISSUE TITLE
more informative pop-up when no tree is found

### ISSUE THREAD

**Issue by hdliv** [phylotastic/Pt_Mobile_Application#79]

**Comment by hdliv** [comment]
![img_1379](https://cloud.githubusercontent.com/assets/6361361/14282169/348b3a0e-fb0b-11e5-9535-783789bbaa0d.jpg)

**Comment by hdliv** [comment]
Scenario:
After 'get tree' the user receives this popup
![img_1379](https://cloud.githubusercontent.com/assets/6361361/14282195/54e3827a-fb0b-11e5-9de6-a164889e64db.jpg)

But when you push ok..you have a blank screen:

![img_1380](https://cloud.githubusercontent.com/assets/6361361/14282219/6cdbc392-fb0b-11e5-9d85-f0368a8f1873.jpg)

When the user presses 'export' they then receive this:
![img_1381](https://cloud.githubusercontent.com/assets/6361361/14282230/7d2805b2-fb0b-11e5-96c3-fa9993c7537b.jpg)

**Comment by arlin** [comment]
I was not able to replicate this.  @hdliv and I are trying to find consistent behavior.

**Comment by hdliv** [comment]
@thanhnh-infinity I think you fixed this in a newer version.  should we move this ticket?

**Comment by thanhnh-infinity** [comment]
Yes, @hdliv

**Comment by hdliv** [comment]
@thanhnh-infinity  moving to done
