### ISSUE TITLE
get mobile app into app store

### ISSUE THREAD

**Issue by arlin** [phylotastic/Pt_Mobile_Application#82]
testflight is a barrier to sharing with non-technical users such as educators.  We want to do a soft release on the app store instead.  

This requires passing Apple's review (https://developer.apple.com/app-store/review/guidelines/), including the human interface guidelines (https://developer.apple.com/library/ios/documentation/userexperience/conceptual/mobilehig/).

**Comment by thanhnh-infinity** [comment]
Dr @arlin , I would like to confirm with you that do you want to release our app on Apple App Store ? If so, I will plan to work on this task.

There are some serious requirements from Apple before the app can be released. 2 above links are very important exam to pass Apple's requirements. In addition, Apple will required many material for app such as : icon in App Store (5 sizes of 5 iphone' screen size), app icons for multiple size, splash-screens for multiple size, prove ownership of data, license, description. I will follow step-by-step to work on that. If there is any issues or problem, I will let you know

**Comment by arlin** [comment]
@thanhnh-infinity, thanks for looking into this.  Here is the situation.  We did not get any feedback from our testers, so we have no idea whether the app is really useful.  This morning, the PIs met to discuss what to do.  We decided that we want to do a soft release, tweet about it with our friends, and share it with some educators.  Maybe some people will find a use for it. In order to do that, we need to put it on the app store, because TestFlight is a barrier for ordinary users.  If you think the process might be too intensive, we can take this out of the "Ready" column and put it into "Backlog" while you discuss it with Dr. Pontelli.  Please talk to him first.

**Comment by thanhnh-infinity** [comment]
Yes, Dr @arlin , I will discuss with professor Pontelli

**Comment by thanhnh-infinity** [comment]
Apple's feedback :  @arlin  @epontell 
17.2 Details

We noticed that your app uses Google login for authentication purposes but does not include account-based features offered by that site, which does not comply with the App Store Review Guidelines.

In order to use Google for authentication, your app must include significant account-specific functionality from Google. For example, your app should include sufficient account-based features from Google other than pulling profile information or sharing on the user’s page.

Next Steps

Please revise your app to implement your own authentication mechanism, or incorporate significant account-specific functionality from Google. 

If your app does include additional account-specific features from Google, please provide us with details on where we can locate these features in your app.

**Comment by thanhnh-infinity** [comment]
@arlin , I received feedback from Apple about Google Authentication that we are using. Dr Pontelli and I discussed about this and Dr Pontelli asked me to remove Authentication on Mobile App. If there is no problem with you, I will remove Authentication and continue submitting for App Store

**Comment by arlin** [comment]
OK, so this means that apple doesn't want us to do the very thing that we wanted to do, which was just to piggy-back off of google's authentication without using their features.  

Can you think of any way to "include sufficient account-based features from Google"?

**Comment by epontell** [comment]
agree, we need to understand. The current app does really not need it (since we do not store/retrieve lists). It is safe to remove authentication in this version while we investigate what they really mean by ‘significant account features’.

Enrico

---

College of Arts & Sciences
New Mexico State University
Las Cruces, NM 88003

**Comment by arlin** [comment]
i put some information about this (including how to search the web for others with the same issue) in the chat room

On May 5, 2016, at 1:48 PM, Enrico Pontelli <notifications@github.com<mailto:notifications@github.com>> wrote:

agree, we need to understand. The current app does really not need it (since we do not store/retrieve lists). It is safe to remove authentication in this version while we investigate what they really mean by ‘significant account features’.

Enrico

---

College of Arts & Sciences
New Mexico State University
Las Cruces, NM 88003

> On May 5, 2016, at 11:15 AM, Arlin Stoltzfus <notifications@github.com<mailto:notifications@github.com>> wrote:
> 
> OK, so this means that apple doesn't want us to do the very thing that we wanted to do, which was just to piggy-back off of google's authentication without using their features.
> 
> Can you think of any way to "include sufficient account-based features from Google"?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub https://github.com/phylotastic/Pt_Mobile_Application/issues/82#issuecomment-217214410

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHubhttps://github.com/phylotastic/Pt_Mobile_Application/issues/82#issuecomment-217223979

---

Arlin Stoltzfus (arlin@umd.edumailto:arlin@umd.edu)
Research Biologist, NIST; Fellow, IBBR; Adj. Assoc. Prof., UMCP
IBBR, 9600 Gudelsky Drive, Rockville, MD, 20850
tel: 240 314 6208; web: www.molevol.orghttp://www.molevol.org

**Comment by thanhnh-infinity** [comment]
I removed Google Authentication and uploaded new version. They sent me a requirement about OpenTree license. So I sent them this link for OpenTree license : https://raw.githubusercontent.com/OpenTreeOfLife/opentree/master/LICENSE.txt

Next, they asked me about one of OpenTree project members, so, I sent the contact of Karen Cranston (karen.cranston@gmail.com , Duke University). Still waiting for Apple review
