### ISSUE TITLE
Android version for class

### ISSUE THREAD

**Issue by hdliv** [phylotastic/Pt_Mobile_Application#86]
have an Android version of the app for classroom exercises

**Comment by hdliv** [comment]
@thanhnh-infinity and I have talked about this issue but just wanted to document it

**Comment by thanhnh-infinity** [comment]
@hdliv Could you try the first version for Android ? 

https://github.com/phylotastic/Pt_Mobile_Application/blob/master/installation/Phylotastic_TreeToGo.apk

**Comment by hdliv** [comment]
@thanhnh-infinity I would need an android fist.  @arlin do you know of someone with an andrioid that we could use for testing

**Comment by arlin** [comment]
sorry, i do not know

**Comment by arlin** [comment]
@\all, someone recommend a cheap android device, and I will buy it off the grant for testing purposes.

**Comment by thanhnh-infinity** [comment]
@arlin  How about budget do you consider ?

**Comment by arlin** [comment]
It depends on how much we are going to use it.  If we can take this to meetings (conferences, meetings with educators) and use it for demonstrations, then maybe it will be worthwhile to spend several hundred dollars to get a nice tablet.  However, if it is just for testing, I want to spend as little as possible.  

On Sep 20, 2016, at 11:46 AM, Thanh Nguyen notifications@github.com wrote:

> @arlin How about budget do you consider ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

---

Arlin Stoltzfus (arlin@umd.edu)
Research Biologist, NIST; Fellow, IBBR; Adj. Assoc. Prof., UMCP
IBBR, 9600 Gudelsky Drive, Rockville, MD, 20850
tel: 240 314 6208; web: www.molevol.org

**Comment by arlin** [comment]
@thanhnh-infinity, do you want to make a recommendation on this?   Something in the range of $100 to $300?

**Comment by thanhnh-infinity** [comment]
I have some phones/tablets, you may consider :

LG Phone : https://www.amazon.com/Unlocked-LG-Phoenix-Flash-Android/dp/B01G4W0I72/ref=sr_1_3?ie=UTF8&qid=1475161452&sr=8-3&keywords=LG+Android+Phone
      or
https://www.amazon.com/LG-G3-Vigor-D725-Smartphone/dp/B00S22T1YE/ref=sr_1_14?ie=UTF8&qid=1475161452&sr=8-14&keywords=LG+Android+Phone

Samsung Phone :  https://www.amazon.com/Samsung-Galaxy-Grand-Prime-G531H/dp/B014LA1M6K/ref=sr_1_5?ie=UTF8&qid=1475161648&sr=8-5&keywords=Samsung+android

Samsung Tablet : https://www.amazon.com/Samsung-Galaxy-8-Inch-Tablet-Titanium/dp/B00V49LL90/ref=sr_1_2?ie=UTF8&qid=1475161711&sr=8-2&keywords=Samsung+android+tablet

**Comment by thanhnh-infinity** [comment]
With Samsung Tablet, I have not found 3G/Wifi version, above tablet is Wifi only

**Comment by arlin** [comment]
Do you think 3G is important?  I was assuming we would just rely on wifi.  What about these? 

https://www.amazon.com/Dragon-Touch-Android-Bluetooth-Unlocked/dp/B014SMN0A2/ref=sr_1_2?s=electronics&ie=UTF8&qid=1475165488&sr=1-2&keywords=tablets+with+free+3g+wifi+android

https://www.amazon.com/Samsung-Sm-T116-Phone-Tablet-Black/dp/B0192FSUR8/ref=sr_1_4?s=electronics&ie=UTF8&qid=1475165636&sr=1-4&keywords=tablet+3g+wifi+android

**Comment by hdliv** [comment]
if you want to go cheaper .  Acer has tablets

**Comment by arlin** [comment]
I have another question.  We want this for two different purposes: testing and demos (showing off the app to stakeholders).  For demos, a tablet is preferable.  But if most users are going to be using phones, then a phone-sized device is better for testing.  What do you think?

**Comment by thanhnh-infinity** [comment]
I think phones are better because most of users are using phones (for both demo and testing) and it has both wifi and 3G.
